### PR TITLE
Support SameSite=None

### PR DESCRIPTION
**Pull request by kwry**
In this PR, "None" can be specified as the value of SameSite attribute.
As background, to support the following announcements of Chrome.
[Cookies with SameSite by default - Chrome Platform Status](https://www.chromestatus.com/feature/5088147346030592)

### CODE REVIEW

**Comment by kwry** [comment]
sorry... I have posted it before writing description. Please wait for a while until writing.

**Comment by kwry** [comment]
The problem that ci is failing has a separate issue. https://github.com/kazeburo/Cookie-Baker/issues/16

**Comment by kazeburo** [comment]
CI problem was fixed.
I merge this.

**Comment by kwry** [comment]
thx!!

**Pull request merged**
